#!/usr/bin/env bash
#installs nginx and configure it on a remote server

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello Wolrd!' > /var/www/html/index.nginx-debian.html
service nginx start
